add a stop command (modified #57)
henkelmax/audio-player pull request #66
Opened 2023-11-27 16:00 UTC by SmajloSlovakian

i just modified https://github.com/henkelmax/audio-player/pull/57 so it works as the original pull request was inactive

2023-11-28 02:29 UTC, ShiftySpace commented
Dang @SmajloSlovakian  thanks a lot! I am still pretty new to coding and also haven't had the time to figure out how I'd need to modify it for the newer versions. Did me a huge favor :D

2023-11-28 06:45 UTC, SmajloSlovakian commented
i'm very new as well... sometimes you just need a clear mind to look at it

2023-11-28 11:52 UTC, henkelmax requested changes

2023-11-28 11:52 UTC, henkelmax commented on src/main/java/de/maxhenkel/audioplayer/command/PlayCommands.java
> +            context.getSource().sendFailure(Component.literal("Failed to stop, Could not find %s".formatted(sound)));
`Failed to stop, could not find sound with ID %s`

2023-11-28 11:52 UTC, henkelmax commented on src/main/java/de/maxhenkel/audioplayer/PlayerManager.java
> +    @Nullable
There should be an empty line

2023-11-28 11:52 UTC, henkelmax commented on src/main/java/de/maxhenkel/audioplayer/command/PlayCommands.java
> +    private static int stop(CommandContext<CommandSourceStack> context, @Name("sound") UUID sound) {
The command currently just stops ALL sounds with that ID. This does not seem to be intentional. It should only stop sounds that were played with the play command. I'd suggest a boolean field marking the sound as a sound that was played with the command and filtering by that.

2023-11-29 19:31 UTC, SmajloSlovakian commented
oh wow how do i approve everything... i clicked on view reviewed changes and checked that i viewed the files and clicked on review changes but i can't approve? do i really have to just make the same changes you proposed and commit them to my fork?

2023-11-29 19:33 UTC, SmajloSlovakian commented
ohh i see how this works... i have to do that because you didn't like edit my code and submit it to me to approve it or somehting... ok... will look at it tomorrow

2023-11-30 15:00 UTC, henkelmax requested changes

2023-11-30 15:00 UTC, henkelmax commented on src/main/java/de/maxhenkel/audioplayer/command/PlayCommands.java
> +            context.getSource().sendFailure(Component.literal("Failed to stop, could not find %s".formatted(sound)));
This still isn't very descriptive. I think `Failed to stop, could not find sound with ID %s` would be better.

2023-11-30 16:32 UTC, SmajloSlovakian commented on src/main/java/de/maxhenkel/audioplayer/command/PlayCommands.java
> +            context.getSource().sendFailure(Component.literal("Failed to stop, could not find %s".formatted(sound)));
ohh.. sorry, i missed the ID part... i just thought that you meant to change the case of the c in "could"

fixed now

2023-11-30 16:48 UTC, merged